services:
  # nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  blue:
    image: fpwjsem/ssulost-server:latest
    container_name: blue-container
    expose:
      - "8080"

  green:
    image: fpwjsem/ssulost-server:latest
    container_name: green-container
    expose:
      - "8081"
