services:
  blue:
    image: ${DOCKER_USERNAME}/ssulost-server:latest
    container_name: blue-container
    ports:
      - "8080:8080"
    environment:
      - MICROMETER_BINDERS_SYSTEM_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  green:
    image: ${DOCKER_USERNAME}/ssulost-server:latest
    container_name: green-container
    ports:
      - "8081:8080"
    environment:
      - MICROMETER_BINDERS_SYSTEM_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
