spring:
  application:
    name: ssu-lost

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  kakao:
    client_id: ${KAKAO_REST_API_KEY}
    redirect_uri: http://localhost:8080/callback/kakao

  google:
    client_id: ${GOOGLE_REST_API_KEY}
    redirect_uri: http://localhost:8080/callback/google
    client_secret: ${GOOGLE_CLIENT_SECRET}

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000

  web:
    resources:
      add-mappings: false
