spring:
  application:
    name: ssu-lost

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  kakao:
    client_id: ${REST_API_KEY}
    redirect_uri: http://localhost:8080/callback/kakao

  web:
    resources:
      add-mappings: false
