name: CI/CD Docker SpringBoot

on:

  workflow_dispatch:

  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate application.yml
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml
          printf '%s' "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Build with gradle
        run: ./gradlew build -x test

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker Image
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/ssulost-server || true
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ssulost-server .

      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ssulost-server

      # EC2에 ssh 접속 후
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USER }}
          key: ${{ secrets.EC2_SERVER_KEY }}
          script: |
            cd /home/ubuntu/bongbaek-server

            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          
            CURRENT_CONF=$(sudo readlink /etc/nginx/sites-enabled/current || echo "")
            
            if [[ "$CURRENT_CONF" == *"blue"* ]]; then
              NEW_SERVICE="green"
              OLD_SERVICE="blue"
              NEW_CONF="/etc/nginx/sites-available/green.conf"
              NEW_PORT=8081
            else
              NEW_SERVICE="blue"
              OLD_SERVICE="green"
              NEW_CONF="/etc/nginx/sites-available/blue.conf"
              NEW_PORT=8080
            fi
            
            echo "🚀 Starting $NEW_SERVICE..."
            docker compose up -d $NEW_SERVICE 
            
            echo "⏳ Waiting for $NEW_SERVICE to be healthy..."
            for i in {1..12}; do
            # 호스트 포트 기준 health 체크
            NEW_PORT=$([ "$NEW_SERVICE" == "blue" ] && echo 8080 || echo 8081)
            STATUS=$(curl -s -f http://localhost:$NEW_PORT/actuator/health >/dev/null 2>&1 && echo "healthy" || echo "starting")
            
            if [ "$STATUS" == "healthy" ]; then
            echo "✅ $NEW_SERVICE is healthy!"
            break
            fi
          
            if [ $i -eq 12 ]; then
            echo "❌ $NEW_SERVICE healthcheck failed after 60s"
            exit 1
            fi
          
            echo "Still starting... ($i/12)"
            sleep 5
            done

            
            # Nginx 전환
            sudo ln -sf $NEW_CONF /etc/nginx/sites-enabled/current
            sudo systemctl reload nginx
            echo "🔄 Nginx switched to $NEW_SERVICE"

            # 구버전 종료 및 정리
            docker compose stop $OLD_SERVICE
            docker compose rm -f $OLD_SERVICE
            docker image prune -f
